# This config file is meant for settings that affect your whole blog, values
#   which you are expected to set up once and rarely edit after that. If you
#   find yourself editing this file very often, consider using Jekyll's data
#   files feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you
#   use `bundle exec jekyll serve`. If you change this file, please restart
#   the server process.
# If you need help with YAML syntax, here are some quick references for you: 
# * [ https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml ];
# * [ https://learnxinyminutes.com/docs/yaml/ ].

# Site settings
title: Estrilda
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    asrelo's Estrilda
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: ru
github_username:  asrelo
license_link: "https://github.com/asrelo/estrilda/blob/master/README.md"

collections:
    c_nav:
        output: true
        permalink: /nav/:name
    c_studying:
        output: true
        permalink: /studying/:name
    c_studying_electrics_notes:
        output: true
        permalink: /studying/electrics-notes/:name
    c_studying_math_notes:
        output: true
        permalink: /studying/math-notes/:name
    c_studying_statistics_notes:
        output: true
        permalink: /studying/statistics-notes/:name

# Build settings
collections_dir: content
# a value from the IANA Time Zone Database:
timezone: Europe/Moscow
# gem theme is not used on this site
#theme: minima
strict_front_matter: true
liquid:
    error_mode: strict
    strict_filters: true
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-spaceship
jekyll-spaceship:
    processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    #- element-processor

# Exclude from processing
# exclude:
#     - .sass-cache/
#     - .jekyll-cache/
#     - gemfiles/
#     - Gemfile
#     - Gemfile.lock
#     - node_modules/
#     - vendor/bundle/
#     - vendor/cache/
#     - vendor/gems/
#     - vendor/ruby/
exclude:
    - dev_notes/
    - fonts/*-LICENSE.txt
    - minima-LICENSE.txt
    - minima-README.md
    - LICENSE.txt
    - README.md

include:
    - robots.txt
    - site.webmanifest
